services:
  3xui:
    image: ${THREEXUI_IMAGE:-ghcr.io/mhsanaei/3x-ui:latest}
    container_name: ${THREEXUI_CONTAINER_NAME:-3xui_app}
    hostname: ${THREEXUI_HOSTNAME:-example.com}
    volumes:
      - ${THREEXUI_DB_DIR:-./db}:/etc/x-ui/
      - ${THREEXUI_CERT_DIR:-./cert}:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped
